# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ed2d4a2405000342d152e15979d3f6e71031a5115829303a6c6510531949c9e855c9bd763662c0b5db5afc750ab3406e8137d8f101434475c81e6fa9bc56840

test:
  secret_key_base: 90a315ecc2f55051c71802349e25358e6bfbefb106a6117acb37b9ed226c945ba0f0891df1e423fd5011a7551c3650b98a1b338aab3033422e130fb6975a6432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
